added products creation tab and general page composition
mmarganski/cook pull request #1
Opened 2021-08-11 12:08 UTC by mmarganski

2021-08-11 12:18 UTC, GrzegorzTarnopolski requested changes

2021-08-11 12:18 UTC, GrzegorzTarnopolski commented on package.json
> +  "name": "todo-react",
cook I guess :D

2021-08-11 12:18 UTC, GrzegorzTarnopolski commented on package.json
> +    "@testing-library/jest-dom": "5.11.4",
@tesing libraries are dev dependencies

2021-08-11 12:18 UTC, GrzegorzTarnopolski commented on src/components/Item.tsx
> +export const Item = (props: {text: string}) => (
we don't write types inline, create type ItemProps

2021-08-11 12:18 UTC, GrzegorzTarnopolski commented on src/components/Main.tsx
> +
5 lines under -> between consts we don't use enter

2021-08-11 12:18 UTC, GrzegorzTarnopolski commented on src/components/NameInput.tsx
> +export const NameInput = (props: {onSubmittedInput(text: string): void}) => {
.

2021-08-11 12:18 UTC, GrzegorzTarnopolski commented on src/components/ProductsTab.tsx
> +
.

2021-08-11 12:18 UTC, GrzegorzTarnopolski commented on src/components/ProductsView.tsx
> +    window.localStorage.setItem('products', `${[...props.products]}`)
```
JSON.Stringify({})
JSON.Parse()
```

2021-08-12 11:26 UTC, GrzegorzTarnopolski requested changes

2021-08-12 11:26 UTC, gtarnopolski commented on src/components/ProductsTab.tsx
> +    const products = JSON.parse(window.localStorage.getItem('products') || '[]')
👍

2021-08-12 11:26 UTC, GrzegorzTarnopolski commented on src/components/ProductsTab.tsx
> +            <ProductsView products={currentState} lastUpdate={''} selectable/>
more than 2 props multiline :)

2021-08-12 11:26 UTC, GrzegorzTarnopolski commented on src/components/ProductsView.tsx
> +                        ? (<Item
```
                                 ? (
                                 <Item
                                      key={`${index}-${product}`}
                                      text={product}
                                    />
                            )  :  (
                                 <SelectWrapper
                                      key={`${index}-${product}`}
                                      text={product}
                                      lastUpdate={props.lastUpdate}
                        />
                     )
```

2021-08-12 11:26 UTC, GrzegorzTarnopolski commented on src/components/RecipesTab.tsx
> +    window.localStorage.removeItem('selected')
this will be triggered each rerender (every time state changes)

2021-08-12 11:26 UTC, GrzegorzTarnopolski commented on src/components/RecipesView.tsx
> +    recipes: any
no any

2021-08-12 11:26 UTC, GrzegorzTarnopolski commented on src/components/RecipesView.tsx
> +    window.localStorage.setItem('recipes', JSON.stringify(props.recipes))
aa

2021-08-12 11:26 UTC, GrzegorzTarnopolski commented on src/components/SelectWrapper.tsx
> +            ? [...currentSelect].filter(element => element !== props.text)
what is that [...currentSelect]

2021-08-13 10:52 UTC, jpudysz requested changes

2021-08-13 10:52 UTC, jpudysz commented on src/App.js
> +import './App.css'
import order

2021-08-13 10:52 UTC, jpudysz commented on src/components/ClickableWrapper.tsx
> +    children: React.ReactChild,
no need to point `children` its already added underneath by `React.FunctionComponent<T>`

2021-08-13 10:52 UTC, jpudysz commented on src/components/Header.tsx
> +export const Header: React.FunctionComponent<HeaderProps> = props => (
we prefer destructiring

2021-08-13 10:52 UTC, jpudysz commented on src/components/Item.tsx
> +export const Item: React.FunctionComponent<ItemProps> = props => (
aa

2021-08-13 10:52 UTC, jpudysz commented on src/components/Main.tsx
> +import { ProductsTab, RecipesTab, SearchTab, TabsBar } from './index'
no `index` imports

2021-08-13 10:52 UTC, jpudysz commented on src/components/Main.tsx
> +    const onSelectTab= (tab: Tab) => {
remove enter (group const) and add space after `onSelectTab`

2021-08-13 10:52 UTC, jpudysz commented on src/components/Main.tsx
> +            case Tab.Search:
can be shortened:
```
case Tab.Search:
default:
           setActiveTab(Tab.Search)
           break
```

2021-08-13 10:52 UTC, jpudysz commented on src/components/Main.tsx
> +                return(<ProductsTab/>)
add spacing:
```
return (
    <RecipesTab/>
)
```

2021-08-13 10:52 UTC, jpudysz commented on src/components/NameInput.tsx
> +export const NameInput: React.FunctionComponent<NameInputProps> = props => {
aa - destructirung

2021-08-13 10:52 UTC, jpudysz commented on src/components/ProductsView.tsx
> +        <Header text={'Products'}/>
magic string + bad syntax for JSX's string

2021-08-13 10:52 UTC, jpudysz commented on src/components/ProductsView.tsx
> +export const ProductsView = (props: ProductsViewProps) => (
aa

2021-08-13 10:52 UTC, jpudysz commented on src/components/RecipesTab.tsx
> +                const storageRecipes =  getStorageRecipes()
remove space

2021-08-13 10:52 UTC, jpudysz commented on src/components/RecipesView.tsx
> +        <Header text="Recipes"/>
magic string

2021-08-13 10:52 UTC, jpudysz commented on src/components/RecipesView.tsx
> +                )}
something went wrong here with the indentation

2021-08-13 10:52 UTC, jpudysz commented on src/components/SearchTab.tsx
> +    const [[activeProducts, activeRecipes], setActiveItems] = useState<Array<Array<string>>>([[], []])
for me it should be moved to two states

2021-08-13 10:52 UTC, jpudysz commented on src/components/SelectWrapper.tsx
> +    <Wrapper onClick={() => props.onSelect(props.text)} isActive={props.isActive}>
one props per line

2021-08-13 10:52 UTC, jpudysz commented on src/components/SelectWrapper.tsx
> +export const SelectWrapper: React.FunctionComponent<SelectWrapperProps> = props => (
aa

2021-08-13 10:52 UTC, jpudysz commented on src/components/TabsBar.tsx
> +export const TabsBar: React.FunctionComponent<TabsBarProps> = props => (
aa

2021-08-13 13:38 UTC, jpudysz requested changes

2021-08-13 13:38 UTC, jpudysz commented on src/components/ClickableWrapper.tsx
> +export const ClickableWrapper: React.FunctionComponent<ClickableWrapperProps> = ({onSelect, children}) => (
you won't like it but you should add additional spaces between `{}` when you destructure :) (everywhere)

2021-08-13 13:38 UTC, jpudysz commented on src/components/ClickableWrapper.tsx
> +export const ClickableWrapper: React.FunctionComponent<ClickableWrapperProps> = ({onSelect, children}) => (
Apart of that, looks great, keep going!

2021-08-16 07:44 UTC, jpudysz requested changes

2021-08-16 07:44 UTC, jpudysz commented on src/components/RecipesTab.tsx
> +                setStorageRecipes({ ...storageRecipes, [text]: activeItems })
split it into 3 lines:
```
setStorageRecipes({
     ...storageRecipes,
     [text]: activeItems   
})
```

2021-08-16 08:37 UTC, GrzegorzTarnopolski approved these changes

2021-08-16 08:37 UTC, jpudysz approved these changes

2021-08-16 08:41 UTC, merged